version: '3.7'

services:
    web :
        image: php:5.6-apache
        container_name: php_web
        depends_on:
            -   mariadb
        ports:
        -   80:80
        volumes:
        -   ./php/:/var/www/html
    mariadb:
        image: library/mariadb:10.5.2
        volumes:
        -   mariadb-volume:/var/lib/mysql

        environment:
            TZ: "Europe/Paris"
            MYSQL_ALLOW_EMPTY_PASSWORD: "no"
            MYSQL_ROOT_PASSWORD: "rootpwd"
            MYSQL_USER: 'test'
            MYSQL_PASSWORD: 'root'
            MYSQL_DATABASE: 'testdb'
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        links:
            -   'mariadb:db'
        ports:
        -   8081:80
volumes:
    mariadb-volume:
